<?php

declare(strict_types=1);

namespace App\Repository;

/**
 * OfferSkillRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferSkillRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDistinctSkills()
    {
        $qb = $this->createQueryBuilder('s');

        return $qb->select('s.label')
            ->distinct()
            ->innerJoin('App\Entity\Offer', 'o', 'WITH', 'o.id = s.offer')
            ->where('o.enabled = :enabledValue')
            ->setParameter('enabledValue', 1)
            ->getQuery()
            ->getResult();
    }
}
